/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAlurSistemRouteImport } from './routes/admin/alur-sistem'
import { Route as AdminDatabaseOrangtuaRouteImport } from './routes/admin/database-orangtua'
import { Route as AdminKonsultasiRouteImport } from './routes/admin/konsultasi'
import { Route as AdminLogAktivitasRouteImport } from './routes/admin/log-aktivitas'
import { Route as AdminPengaturanRouteImport } from './routes/admin/pengaturan'
import { Route as AdminPertanyaanRouteImport } from './routes/admin/pertanyaan'
import { Route as AdminPromptRouteImport } from './routes/admin/prompt'
import { Route as AdminTestingRouteImport } from './routes/admin/testing'
import { Route as FormulirJenjangRouteImport } from './routes/formulir.$jenjang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlurSistemRoute = AdminAlurSistemRouteImport.update({
  id: '/alur-sistem',
  path: '/alur-sistem',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDatabaseOrangtuaRoute = AdminDatabaseOrangtuaRouteImport.update({
  id: '/database-orangtua',
  path: '/database-orangtua',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKonsultasiRoute = AdminKonsultasiRouteImport.update({
  id: '/konsultasi',
  path: '/konsultasi',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogAktivitasRoute = AdminLogAktivitasRouteImport.update({
  id: '/log-aktivitas',
  path: '/log-aktivitas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPertanyaanRoute = AdminPertanyaanRouteImport.update({
  id: '/pertanyaan',
  path: '/pertanyaan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromptRoute = AdminPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestingRoute = AdminTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FormulirJenjangRoute = FormulirJenjangRouteImport.update({
  id: '/formulir/$jenjang',
  path: '/formulir/$jenjang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sukses': typeof SuksesRoute
  '/admin/alur-sistem': typeof AdminAlurSistemRoute
  '/admin/database-orangtua': typeof AdminDatabaseOrangtuaRoute
  '/admin/konsultasi': typeof AdminKonsultasiRoute
  '/admin/log-aktivitas': typeof AdminLogAktivitasRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pertanyaan': typeof AdminPertanyaanRoute
  '/admin/prompt': typeof AdminPromptRoute
  '/admin/testing': typeof AdminTestingRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sukses': typeof SuksesRoute
  '/admin/alur-sistem': typeof AdminAlurSistemRoute
  '/admin/database-orangtua': typeof AdminDatabaseOrangtuaRoute
  '/admin/konsultasi': typeof AdminKonsultasiRoute
  '/admin/log-aktivitas': typeof AdminLogAktivitasRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pertanyaan': typeof AdminPertanyaanRoute
  '/admin/prompt': typeof AdminPromptRoute
  '/admin/testing': typeof AdminTestingRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sukses': typeof SuksesRoute
  '/admin/alur-sistem': typeof AdminAlurSistemRoute
  '/admin/database-orangtua': typeof AdminDatabaseOrangtuaRoute
  '/admin/konsultasi': typeof AdminKonsultasiRoute
  '/admin/log-aktivitas': typeof AdminLogAktivitasRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pertanyaan': typeof AdminPertanyaanRoute
  '/admin/prompt': typeof AdminPromptRoute
  '/admin/testing': typeof AdminTestingRoute
  '/formulir/$jenjang': typeof FormulirJenjangRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sukses'
    | '/admin/alur-sistem'
    | '/admin/database-orangtua'
    | '/admin/konsultasi'
    | '/admin/log-aktivitas'
    | '/admin/pengaturan'
    | '/admin/pertanyaan'
    | '/admin/prompt'
    | '/admin/testing'
    | '/formulir/$jenjang'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sukses'
    | '/admin/alur-sistem'
    | '/admin/database-orangtua'
    | '/admin/konsultasi'
    | '/admin/log-aktivitas'
    | '/admin/pengaturan'
    | '/admin/pertanyaan'
    | '/admin/prompt'
    | '/admin/testing'
    | '/formulir/$jenjang'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/sukses'
    | '/admin/alur-sistem'
    | '/admin/database-orangtua'
    | '/admin/konsultasi'
    | '/admin/log-aktivitas'
    | '/admin/pengaturan'
    | '/admin/pertanyaan'
    | '/admin/prompt'
    | '/admin/testing'
    | '/formulir/$jenjang'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuksesRoute: typeof SuksesRoute
  FormulirJenjangRoute: typeof FormulirJenjangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/alur-sistem': {
      id: '/admin/alur-sistem'
      path: '/alur-sistem'
      fullPath: '/admin/alur-sistem'
      preLoaderRoute: typeof AdminAlurSistemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/database-orangtua': {
      id: '/admin/database-orangtua'
      path: '/database-orangtua'
      fullPath: '/admin/database-orangtua'
      preLoaderRoute: typeof AdminDatabaseOrangtuaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/konsultasi': {
      id: '/admin/konsultasi'
      path: '/konsultasi'
      fullPath: '/admin/konsultasi'
      preLoaderRoute: typeof AdminKonsultasiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/log-aktivitas': {
      id: '/admin/log-aktivitas'
      path: '/log-aktivitas'
      fullPath: '/admin/log-aktivitas'
      preLoaderRoute: typeof AdminLogAktivitasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pertanyaan': {
      id: '/admin/pertanyaan'
      path: '/pertanyaan'
      fullPath: '/admin/pertanyaan'
      preLoaderRoute: typeof AdminPertanyaanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prompt': {
      id: '/admin/prompt'
      path: '/prompt'
      fullPath: '/admin/prompt'
      preLoaderRoute: typeof AdminPromptRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testing': {
      id: '/admin/testing'
      path: '/testing'
      fullPath: '/admin/testing'
      preLoaderRoute: typeof AdminTestingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/formulir/$jenjang': {
      id: '/formulir/$jenjang'
      path: '/formulir/$jenjang'
      fullPath: '/formulir/$jenjang'
      preLoaderRoute: typeof FormulirJenjangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAlurSistemRoute: typeof AdminAlurSistemRoute
  AdminDatabaseOrangtuaRoute: typeof AdminDatabaseOrangtuaRoute
  AdminKonsultasiRoute: typeof AdminKonsultasiRoute
  AdminLogAktivitasRoute: typeof AdminLogAktivitasRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPertanyaanRoute: typeof AdminPertanyaanRoute
  AdminPromptRoute: typeof AdminPromptRoute
  AdminTestingRoute: typeof AdminTestingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAlurSistemRoute: AdminAlurSistemRoute,
  AdminDatabaseOrangtuaRoute: AdminDatabaseOrangtuaRoute,
  AdminKonsultasiRoute: AdminKonsultasiRoute,
  AdminLogAktivitasRoute: AdminLogAktivitasRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPertanyaanRoute: AdminPertanyaanRoute,
  AdminPromptRoute: AdminPromptRoute,
  AdminTestingRoute: AdminTestingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SuksesRoute: SuksesRoute,
  FormulirJenjangRoute: FormulirJenjangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
